version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: 'mongodb+srv://arpitkrishna930:fNBMW1168fbRhIBq@cluster71511.erbcyxl.mongodb.net/Expences?retryWrites=true&w=majority'


volumes:
  mongo_data:
